#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/TOKEN_HERE
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
    metadata: region=nyc,location=nyc3,public_ip=$public_ipv4,host=coreos61,size=1gb,image=stable
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

# NEEDED
# - Add private key to use for Core user to work with other services online
# - Expand the metadata information to add additional informaiton per the CoreOS.com doc