#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/5d1dffbbac923b1da664eed1f2255fd7
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
    metadata: region=nyc,location=nyc3,public_ip=$public_ipv4,host=coreos61,image=stable
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
